import { GoogleGenAI, Modality } from "@google/genai";

const API_KEY = process.env.API_KEY;

if (!API_KEY) {
  throw new Error("API_KEY environment variable not set");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });

const fileDataToPart = (data: string) => {
  const [header, base64Data] = data.split(",");
  const mimeType = header.match(/:(.*?);/)?.[1] ?? "image/jpeg";
  return {
    inlineData: {
      mimeType,
      data: base64Data,
    },
  };
};

export const generateTryOnImage = async (
  userImage: string,
  outfitImage: string
): Promise<string> => {
  const prompt = `
    As an expert in photorealistic image editing, your task is to combine two images: a person's photo and a clothing item's photo.
    
    Instructions:
    1.  **Pose Alignment:** Automatically align the outfit with the user’s body pose. The clothing should drape and fold naturally according to the person's stance.
    2.  **Body Fit Estimation:** Intelligently adjust the outfit's size and proportions to realistically fit the user's body shape. Avoid distortion.
    3.  **Lighting Correction:** Seamlessly match the lighting, shadows, and color tones of the outfit to the user's photo environment. The final image must look like it was taken in a single shot.
    4.  **Perspective Matching:** The outfit should be rendered from a front view to match the user's orientation.
    5.  **Output:** Produce a single, high-quality, photorealistic image of the person wearing the outfit. Do not include any text or annotations.
  `;

  const userImagePart = fileDataToPart(userImage);
  const outfitImagePart = fileDataToPart(outfitImage);

  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
      parts: [
        { text: prompt },
        userImagePart,
        outfitImagePart,
      ],
    },
    config: {
      responseModalities: [Modality.IMAGE],
    },
  });

  for (const part of response.candidates[0].content.parts) {
    if (part.inlineData) {
      const base64ImageBytes = part.inlineData.data;
      const mimeType = part.inlineData.mimeType;
      return `data:${mimeType};base64,${base64ImageBytes}`;
    }
  }

  throw new Error("No image was generated by the API.");
};


export const generateAIFeedback = async (
  userImage: string,
  outfitImage: string,
): Promise<string> => {
    const prompt = `Based on the person in the first image and the outfit in the second, provide a short, positive, and encouraging fashion feedback statement in 1-2 sentences. Example: "This outfit suits you!" or "The color of this piece really complements your style!"`;

    const userImagePart = fileDataToPart(userImage);
    const outfitImagePart = fileDataToPart(outfitImage);

    const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash',
        contents: {
            parts: [
                { text: prompt },
                userImagePart,
                outfitImagePart,
            ],
        },
    });

    return response.text;
}